### ISSUE TITLE
Data is same for fonzer and fonzee on My profile.whats the use of two tabs.

### ISSUE THREAD

**Issue by Nikitamisra** [ramankapur/Fonzee-Android#103]

**Comment by adityabandral** [comment]
@Nikitamisra This was client's requirement. The only difference we have is the top info. When we switch the profiles, ratings and other data associated gets changed

**Comment by Nikitamisra** [comment]
"About me" has to be different for both. Fonzer will never represent himself as fonzee profile. You can confirm with client.

**Comment by adityabandral** [comment]
@Nikitamisra For now, client has asked for same info. While applying for a Chore he can explain all the details.

**Comment by Nikitamisra** [comment]
okay as you say it is client req closing the issue
