### ISSUE TITLE
UI changes on Registration Page

### ISSUE THREAD

**Issue by Nikitamisra** [ramankapur/Fonzee-Android#14]
Please correct the following UI issues :+1: 
1. Space required between Confirm password and Upload Id Proof 
2.  If Id proof is two , evenly place them 
3. Register button should be as per the screen. increase the length of registration.

**Comment by Nikitamisra** [comment]
I'll verify the issue in next build and Ill close it.

**Comment by poojatrantor** [comment]
Fixed

**Comment by Nikitamisra** [comment]
verified
