### ISSUE TITLE
Password getting changed even if wrong old password is entered 

### ISSUE THREAD

**Issue by Nikitamisra** [ramankapur/Fonzee-Android#19]
Login the app
click on change password 
Enter old password  as 'dgfjgdjf' (wrong)
Enter New password and confirm password 
Click on submit button 

Expected result :  Message should be displayed 'wrong Old Password entered '
Actual Result : Password getting changed even if wrong old password is entered

**Comment by poojatrantor** [comment]
This is server side issue.

**Comment by Nikitamisra** [comment]
Assigned to Aditya and sarika on Fonzee-Web repository
