### ISSUE TITLE
Toast message is displaying on Register page for Email Id field even if there are no spaces in Email Id

### ISSUE THREAD

**Issue by Nikitamisra** [ramankapur/Fonzee-Android#30]
Go to Registration Page 
Enter the email Id by selecting auto correct ID

Result: Toast message is displaying on Register page for Email Id field even if there are no spaces in Email Id

**Comment by neel-trantor** [comment]
Done.
Now you can't see the auto-correct option while enter email id.

**Comment by Nikitamisra** [comment]
verified
