### ISSUE TITLE
Cell Number Field is not showing the exact digits which user is entering 

### ISSUE THREAD

**Issue by Nikitamisra** [ramankapur/Fonzee-Android#31]
Go to Register Page 
click on Cell number field 
enter cell number as "9876123459"

Result : It will automatically be typed as (998) 987-9876

**Comment by neel-trantor** [comment]
It is not a bug, It is US format cell number as directed by client.   @Nikitamisra

**Comment by Nikitamisra** [comment]
I am not talking about the format. I am not able to enter my full number. In case I'll enter 
99 only first two digits it will enter 999 three digits. Please read the description again.

**Comment by hmittal90** [comment]
Done

**Comment by Nikitamisra** [comment]
verified
