### ISSUE TITLE
Problem with FEIN & TEIN fields , not getting saved

### ISSUE THREAD

**Issue by Nikitamisra** [ramankapur/Fonzee-Android#39]

**Comment by Nikitamisra** [comment]
On My Profile 
Fill the fields FEIN & TEIN fields 
Click on Edit button to save 

Result : Not getting saved

**Comment by neel-trantor** [comment]
This was a back-end issue, and now it is resolved.

**Comment by Nikitamisra** [comment]
It is not resolved. FEIN and TEIN values are not displayed

**Comment by neel-trantor** [comment]
done

**Comment by Nikitamisra** [comment]
verified
