### ISSUE TITLE
High severity -App is on loading when on my profile page Id proof are saved 

### ISSUE THREAD

**Issue by Nikitamisra** [ramankapur/Fonzee-Android#43]
Login with Mike@mailinator.com
pwd - 123456

go to My profile 
upload the Id proof photos from Library 
Click on Edit button 

Result : Loading will be displayed

**Comment by neel-trantor** [comment]
done

**Comment by Nikitamisra** [comment]
Now app is getting crashed

**Comment by neel-trantor** [comment]
done

**Comment by Nikitamisra** [comment]
verified
