### ISSUE TITLE
In case user want to enter 100.50 hours then Ill not be able to enter in chore estimated hours 

### ISSUE THREAD

**Issue by Nikitamisra** [ramankapur/Fonzee-Android#45]
1. Post a chore 
2. Go to chore estimated hours 
3. enter 1000 or 100.

In case user want to enter 100.50 hours then Ill not be able to enter

**Comment by neel-trantor** [comment]
As of now we allow to enter as many digits, but we have to discuss with client about what will be limit in estimated hour.

**Comment by Nikitamisra** [comment]
verified
